### ISSUE TITLE
Issue with reading large dataset

### ISSUE THREAD

**Issue by dnaragan** [adityamnk/timbir#6]
Changes in example file: number of rows (2048), columns (2048), projections (1801) and the rot_center (1024)

Error recorded in debug.log:
###### 

ERROR: read_command_line_args: Argument list has an error
main: Number of nodes is 1 and command line input argument values are proj_rows = 2048, proj_cols = 2048, proj_num = 1801, recon_num = 1, vox_wid = 1.000000, rot_center = 1024.000000, sig_s = 0.010000, sig_t = 1.000000, c_s = 0.000010, c_t = 0.000010, convg_thresh = 1.000000, remove_rings = 0, quad_convex = 1, huber_delta = 0.500000, huber_T = 4.000000, restart = 0
main: Allocating memory for data ....
main: Reading data ....
ERROR: read_BinFile: Read -536573708 number of elements from the file projections at an offset of 0 bytes.
. However, required number of elements is 4194304.
######

**Comment by adityamnk** [comment]
I imagine this issue must be fixed with one of my recent commits. Some integer variables were overflowing for really large datasets.
